- name: install basic utils, shells, apps
  community.general.pacman:
   name:
    - yay
    - downgrade
    - vlc
    - gimp
    - git
    - thefuck
    - tmux
    - lsd
    - vim
    - source-highlight
    - tree
    - base-devel
   state: present

- name: Install archival utils
  pacman:
    name:
      - p7zip
      - unrar
      - unzip
      - zip
      - bzip2
      - gzip
      - tar
    state: present

- name: Install download utils
  pacman:
    name:
      - curl
      - wget
    state: present

- name: Install my tools
  pacman:
    name:
      - htop
      - alacritty
      - encfs
      - owncloud-client
      - pycharm-community-edition
      - qgis
      - steam
      - telegram-desktop
    state: present
