# Update the system
- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes

# Configure pacman (colorize and repos)
- include_tasks: pacman.yml

# Basic apps
- include_tasks: core-apps.yml

# Install and configure zsh
- include_tasks: zsh.yml
  when: setup_zsh == True

# Install and configure spacevim
- include_tasks: spacevim.yml
  when: install_spacevim == True
  
# AUR apps
- include_tasks: aur.yml

# Dotfiles
- include_tasks: dotfiles.yml
  when: pull_dotfiles == True
